#ifndef QEVENTDISPATCHERLIBUV_GLOBAL_H
#define QEVENTDISPATCHERLIBUV_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QEVENTDISPATCHERLIBUV_LIBRARY)
#  define QEVENTDISPATCHERLIBUV_EXPORT Q_DECL_EXPORT
#else
#  define QEVENTDISPATCHERLIBUV_EXPORT Q_DECL_IMPORT
#endif

#endif // QEVENTDISPATCHERLIBUV_GLOBAL_H
